- name: Install Apache 2 host and setup start page
  hosts: testhost    # fill this here
  remote_user: ansibleworkshop # fill this here
  become: yes 
  vars:
    demo_photo: csc_logo.jpg
    demo_greeting: "CSC - IT Center for Science" # you can change the greeting if you like :-)



  tasks:
   - name: Install a webserver
     yum: name=httpd state=present

   - name: Deploy demo web page
     template: src=templates/demo.html.j2 dest=/var/www/html/index.html owner=apache group=apache mode=0644

   - name: Copy  CSC's logo
     copy: src=resources/csc_logo.jpg dest=/var/www/html/csc_logo.jpg owner=apache group=apache mode=0644

   - name: Install firewalld
     yum: name=firewalld state=present

   - name: Start firewalld
     service: name=firewalld state=started enabled=yes sleep=10

   - name: Wait for firewalld
     pause: seconds=30

   - name: Configure firewalld for ssh
     firewalld: service=ssh permanent=true state=enabled
     notify:
       - restart firewalld

   - name: Configure firewalld for http
     firewalld: service=http permanent=true state=enabled
     notify:
       - restart firewalld

   - name: Start apache
     service: name=httpd state=started enabled=yes

  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted sleep=5
