---
sudo: false
language: python
env:
  - ANSIBLE=2.5
before_script:
  - pip install ansible ansible-lint
script: 
  # non-zero return code in script phase fails the build
  - 'ansible-playbook --syntax-check intro-workshop/apache2/*.yml'
  - 'ansible-playbook --syntax-check intro-workshop/sysadmin/playbooks/*.yml'
  #- ansible-lint too?
