---
- name: Setup ssh conf on our node and restart sshd
  hosts: pouta 
  remote_user: cloud-user
  become: yes
  tasks:
    - name: Copy secured sshd config template
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
      notify: reload-sshd

  handlers:
    - name: reload-sshd
      service:
        name: sshd
        state: reloaded
        enabled: yes
