- src: https://github.com/dochang/ansible-role-docker.git
  scm: git
  path: roles

- src: https://github.com/futurice/ansible-pip.git
  scm: git
  path: roles
  name: ansible-role-pip

- src: https://github.com/geerlingguy/ansible-role-nodejs.git
  scm: git
  path: roles
