---
- src: https://github.com/CSCfi/ansible-role-users
  scm: git
  path: roles
  version: master
- src: https://github.com/CSCfi/ansible-role-hosts-inventory
  scm: git
  path: roles
- src: https://github.com/willshersystems/ansible-sshd
  path: roles
  name: ansible-role-sshd
...
