---
- name: check that we have read README
  hosts: localhost
  connection: local
  become: no
  gather_facts: False
  tasks:
    - name: stat ../group_vars/ansible_nodes/vault.yml
      stat:
        path: ../group_vars/ansible_nodes/vault.yml
      register: reg_vault_path
    - name: Fail if ../group_vars/ansible_nodes/vault.yml does not exist
      debug:
        var: reg_vault_path.stat.exists
      failed_when: reg_vault_path.stat.exists == False
    - name: stat ../cm_socket and fail if it does not
      stat:
        path: ../cm_socket
      register: reg_cm_path
      failed_when: reg_cm_path.stat.exists == False
