---
- import_playbook: playbooks/safety_check.yml
- import_playbook: playbooks/build-heat-stack.yml
- import_playbook: playbooks/configure-bastion.yml
- import_playbook: playbooks/configre-bastion-after-forloop.yml
